---
- name: Install samba packages
  apt:
    update_cache: yes
    autoremove: yes
    state: latest
    name:
      - samba
      - samba-common-bin
      - smbclient

- name: Create directory for NAS
  file: { path: /media/NAS, state: directory }
  tags: [ disk ]

- name: '/etc/fstab'
  lineinfile:
    path: /etc/fstab
    line: '/dev/sda1 /media/NAS ntfs nls-utf8,umask-0222,uid-1000,gid-1000,ro 0 0'
    regexp: ^.*\/media/NAS
  register: fstab
  tags: [ disk, fstab ]

- name: Samba configuration
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [administrator]
        path = /media/NAS
        writeable=Yes
        create mask=0775
        directory mask=0775
        public=no

      [antonio]
        path = /media/NAS/antonio
        writeable=Yes
        create mask=0775
        directory mask=0775
        public=no

- name: allow Samba
  ufw:
    rule: allow
    port: Samba
    proto: tcp
