---
- name: Copy install script
  template:
    src: install.sh.j2
    dest: "{{ home_dir }}/noip_install.sh"
    mode: 0744

- name: Install noip
  shell: ./noip_install.sh creates={{noip_conf}}

- name: Install noip init.d
  template:
    src: initd.j2 
    dest: "{{ noip_initd }}"
    mode: 0700

- name: Copy noip2.service
  copy:
    src: noip2.service
    dest: /etc/systemd/system/noip2.service

- name: Enable service noip2
  systemd:
    name: noip2
    enabled: yes

- name: Init service noip2
  systemd:
    name: noip2
    state: started

- name: Rebooting
  shell: reboot -i
